package com.boco.common.soapClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-09T16:35:52.460+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://webservice.fjzl.wondersgroup.com/", name = "ZhuanzhenInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface ZhuanzhenInterface {

    @WebMethod
    @RequestWrapper(localName = "inpatientApply", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.InpatientApply")
    @ResponseWrapper(localName = "inpatientApplyResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.InpatientApplyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String inpatientApply(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "outpatientDetail", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.OutpatientDetail")
    @ResponseWrapper(localName = "outpatientDetailResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.OutpatientDetailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String outpatientDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "inpatientAction", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.InpatientAction")
    @ResponseWrapper(localName = "inpatientActionResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.InpatientActionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String inpatientAction(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "inpatientDetail", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.InpatientDetail")
    @ResponseWrapper(localName = "inpatientDetailResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.InpatientDetailResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String inpatientDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "outpatientApply", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.OutpatientApply")
    @ResponseWrapper(localName = "outpatientApplyResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.OutpatientApplyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String outpatientApply(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "outpatientAction", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.OutpatientAction")
    @ResponseWrapper(localName = "outpatientActionResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.OutpatientActionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String outpatientAction(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "inpatientList", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.InpatientList")
    @ResponseWrapper(localName = "inpatientListResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.InpatientListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String inpatientList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "outpatientList", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.OutpatientList")
    @ResponseWrapper(localName = "outpatientListResponse", targetNamespace = "http://webservice.fjzl.wondersgroup.com/", className = "com.boco.common.soapClient.OutpatientListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String outpatientList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
