package com.boco.common.soapClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-09T16:35:52.479+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "ZhuanzhenImplService", 
                  wsdlLocation = "http://218.89.178.119:8088/fjzl/webservice/zhuanzhen?wsdl",
                  targetNamespace = "http://webservice.fjzl.wondersgroup.com/") 
public class ZhuanzhenImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.fjzl.wondersgroup.com/", "ZhuanzhenImplService");
    public final static QName ZhuanzhenImplPort = new QName("http://webservice.fjzl.wondersgroup.com/", "ZhuanzhenImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://218.89.178.119:8088/fjzl/webservice/zhuanzhen?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZhuanzhenImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://218.89.178.119:8088/fjzl/webservice/zhuanzhen?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZhuanzhenImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZhuanzhenImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZhuanzhenImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZhuanzhenImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZhuanzhenImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZhuanzhenImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZhuanzhenInterface
     */
    @WebEndpoint(name = "ZhuanzhenImplPort")
    public ZhuanzhenInterface getZhuanzhenImplPort() {
        return super.getPort(ZhuanzhenImplPort, ZhuanzhenInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZhuanzhenInterface
     */
    @WebEndpoint(name = "ZhuanzhenImplPort")
    public ZhuanzhenInterface getZhuanzhenImplPort(WebServiceFeature... features) {
        return super.getPort(ZhuanzhenImplPort, ZhuanzhenInterface.class, features);
    }

}
