package com.boco.common.soapClient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1 2017-11-09T16:35:52.417+08:00
 * Generated source version: 3.2.1
 * 
 */
public final class ZhuanzhenInterface_ZhuanzhenImplPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://webservice.fjzl.wondersgroup.com/", "ZhuanzhenImplService");

	private ZhuanzhenInterface_ZhuanzhenImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = ZhuanzhenImplService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		ZhuanzhenImplService ss = new ZhuanzhenImplService(wsdlURL,
				SERVICE_NAME);
		ZhuanzhenInterface port = ss.getZhuanzhenImplPort();

		{
			System.out.println("Invoking inpatientApply...");
			java.lang.String _inpatientApply_arg0 = "";
			java.lang.String _inpatientApply_arg1 = "";
			java.lang.String _inpatientApply__return = port.inpatientApply(
					_inpatientApply_arg0, _inpatientApply_arg1);
			System.out.println("inpatientApply.result="
					+ _inpatientApply__return);

		}
		{
			System.out.println("Invoking outpatientDetail...");
			java.lang.String _outpatientDetail_arg0 = "";
			java.lang.String _outpatientDetail_arg1 = "";
			java.lang.String _outpatientDetail__return = port.outpatientDetail(
					_outpatientDetail_arg0, _outpatientDetail_arg1);
			System.out.println("outpatientDetail.result="
					+ _outpatientDetail__return);

		}
		{
			System.out.println("Invoking inpatientAction...");
			java.lang.String _inpatientAction_arg0 = "";
			java.lang.String _inpatientAction_arg1 = "";
			java.lang.String _inpatientAction__return = port.inpatientAction(
					_inpatientAction_arg0, _inpatientAction_arg1);
			System.out.println("inpatientAction.result="
					+ _inpatientAction__return);

		}
		{
			System.out.println("Invoking inpatientDetail...");
			java.lang.String _inpatientDetail_arg0 = "";
			java.lang.String _inpatientDetail_arg1 = "";
			java.lang.String _inpatientDetail__return = port.inpatientDetail(
					_inpatientDetail_arg0, _inpatientDetail_arg1);
			System.out.println("inpatientDetail.result="
					+ _inpatientDetail__return);

		}
		{
			System.out.println("Invoking outpatientApply...");
			java.lang.String _outpatientApply_arg0 = "";
			java.lang.String _outpatientApply_arg1 = "";
			java.lang.String _outpatientApply__return = port.outpatientApply(
					_outpatientApply_arg0, _outpatientApply_arg1);
			System.out.println("outpatientApply.result="
					+ _outpatientApply__return);

		}
		{
			System.out.println("Invoking outpatientAction...");
			java.lang.String _outpatientAction_arg0 = "";
			java.lang.String _outpatientAction_arg1 = "";
			java.lang.String _outpatientAction__return = port.outpatientAction(
					_outpatientAction_arg0, _outpatientAction_arg1);
			System.out.println("outpatientAction.result="
					+ _outpatientAction__return);

		}
		{
			System.out.println("Invoking inpatientList...");
			java.lang.String _inpatientList_arg0 = "";
			java.lang.String _inpatientList_arg1 = "";
			java.lang.String _inpatientList__return = port.inpatientList(
					_inpatientList_arg0, _inpatientList_arg1);
			System.out
					.println("inpatientList.result=" + _inpatientList__return);

		}
		{
			System.out.println("Invoking outpatientList...");
			java.lang.String _outpatientList_arg0 = "{\"zcjgdm\":\"MYDSF004\",\"zcjgmc\":\"亿阳信通股份有限公司\",\"bdjgdm\":\"PDY00001X510700\",\"bdjgmc\":\"绵阳市卫生和计划生育委员会\",\"bdyydm\":\"YYXTFJZL001\",\"bdyymc\":\"亿阳信通分级诊疗系统\",\"jkdm\":\"CDSXZZ0002\",\"jkmc\":\"outpatientList\",\"username\":\"yiyangxintong\",\"password\":\"111111\",\"bdczxtdm\":\"windows\",\"bdczxtmc\":\"windows\"}";
			java.lang.String _outpatientList_arg1 = "{\"mzzz_fqyydm\":\"877ff477h441\",\"pageNo\":1,\"pageSize\":5}";
			java.lang.String _outpatientList__return = port.outpatientList(
					_outpatientList_arg0, _outpatientList_arg1);
			System.out.println("outpatientList.result="
					+ _outpatientList__return);

		}

		System.exit(0);
	}

}
