
package com.boco.common.soapClient;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-09T16:35:52.473+08:00
 * Generated source version: 3.2.1
 * 
 */
 
public class ZhuanzhenInterface_ZhuanzhenImplPort_Server{

    protected ZhuanzhenInterface_ZhuanzhenImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ZhuanzhenImplPortImpl();
        String address = "http://218.89.178.119:8088/fjzl/webservice/zhuanzhen";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ZhuanzhenInterface_ZhuanzhenImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
