
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.boco.common.soapClient;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-11-09T16:35:52.441+08:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZhuanzhenImplService",
                      portName = "ZhuanzhenImplPort",
                      targetNamespace = "http://webservice.fjzl.wondersgroup.com/",
                      wsdlLocation = "http://218.89.178.119:8088/fjzl/webservice/zhuanzhen?wsdl",
                      endpointInterface = "com.boco.common.soapClient.ZhuanzhenInterface")
                      
public class ZhuanzhenImplPortImpl implements ZhuanzhenInterface {

    private static final Logger LOG = Logger.getLogger(ZhuanzhenImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.boco.common.soapClient.ZhuanzhenInterface#inpatientApply(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String inpatientApply(java.lang.String arg0, java.lang.String arg1) { 
        LOG.info("Executing operation inpatientApply");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.boco.common.soapClient.ZhuanzhenInterface#outpatientDetail(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String outpatientDetail(java.lang.String arg0, java.lang.String arg1) { 
        LOG.info("Executing operation outpatientDetail");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.boco.common.soapClient.ZhuanzhenInterface#inpatientAction(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String inpatientAction(java.lang.String arg0, java.lang.String arg1) { 
        LOG.info("Executing operation inpatientAction");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.boco.common.soapClient.ZhuanzhenInterface#inpatientDetail(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String inpatientDetail(java.lang.String arg0, java.lang.String arg1) { 
        LOG.info("Executing operation inpatientDetail");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.boco.common.soapClient.ZhuanzhenInterface#outpatientApply(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String outpatientApply(java.lang.String arg0, java.lang.String arg1) { 
        LOG.info("Executing operation outpatientApply");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.boco.common.soapClient.ZhuanzhenInterface#outpatientAction(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String outpatientAction(java.lang.String arg0, java.lang.String arg1) { 
        LOG.info("Executing operation outpatientAction");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.boco.common.soapClient.ZhuanzhenInterface#inpatientList(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String inpatientList(java.lang.String arg0, java.lang.String arg1) { 
        LOG.info("Executing operation inpatientList");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.boco.common.soapClient.ZhuanzhenInterface#outpatientList(java.lang.String arg0, java.lang.String arg1)*
     */
    public java.lang.String outpatientList(java.lang.String arg0, java.lang.String arg1) { 
        LOG.info("Executing operation outpatientList");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
